import type { Metadata } from "next";
import ProvidersChakra from "@/providers/ProvidersChakra";
import { roboto } from "./fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={`${roboto.variable}`}>
      <ProvidersChakra>
        {children}
      </ProvidersChakra>
      </body>
    </html>
  );
}
